@echo off
REM Robocopy commands to mirror cataloged files to local storage
REM Generated by Corpus Cataloger

REM Source: S:\
REM Destination: C:\Users\brand\Projects\Server
REM Total files: 65,408
REM Total size: 238.49 GB

echo Starting file copy...
echo.

REM Copy all files from S:\ to destination
REM /MIR = Mirror (copy all, remove extra)
REM /MT:n = Multi-threaded (n threads)
REM /R:2 = Retry 2 times on failed copies
REM /W:5 = Wait 5 seconds between retries
REM /BYTES = Show sizes in bytes
REM /TEE = Output to console and log file
REM /LOG = Log file

REM Option 1: FULL MIRROR - Fastest, copies everything, removes extra files
robocopy "S:\" "C:\Users\brand\Projects\Server" /MIR /MT:8 /R:2 /W:5 /BYTES /TEE /LOG:robocopy_full.log

REM Option 2: COPY ONLY - Doesn't delete extra files at destination
REM robocopy "S:\" "C:\Users\brand\Projects\Server" /E /MT:8 /R:2 /W:5 /BYTES /TEE /LOG:robocopy_copy.log

REM Option 3: UPDATE ONLY - Skip files that exist and are same size/date
REM robocopy "S:\" "C:\Users\brand\Projects\Server" /E /XO /MT:8 /R:2 /W:5 /BYTES /TEE /LOG:robocopy_update.log

echo.
echo Copy complete!
echo Check robocopy_full.log for details
pause
